[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.19"
optimizer = true
optimizer_runs = 200
via_ir = false

[rpc_endpoints]
mainnet = "https://rpc.ankr.com/eth"
polygon = "https://rpc.ankr.com/polygon"
arbitrum = "https://rpc.ankr.com/arbitrum"

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

[doc]
out = "docs"
title = "1inch Advanced Strategy Engine"
